### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by fhennig** [anzbert/rusty_link#7] opened 2022-10-19 16:05 UTC
Hey, I _just_ found this libary while looking at the `ableton_link` library, thanks for making it! I'm building it on a Mac M1, works great! Also thanks for porting the example, very nice!

**Comment by anzbert** [comment] 2022-10-19 23:30
hey no probs :) 
i am still ironing out the kinks in the example with sound. that one doesnt really reflect best practices yet, for example it uses the link instance as a global static, which may be iffy ?!. (Maybe an Arc<> instead?) . it pretty much works though 😅, even though i havn't tested it on platforms outside of the mac yet.

i am not 100% sure yet about the API design yet. i am considering different ways to make it more rusty without making it too restrictive. i still want to leave it to the user how they want to implement the library.

i am happy to get some help with it too :)

**Comment by anzbert** [comment] 2022-10-20 21:57
I'll update the library in a few days with the host time filter from Ableton (just a simple linear regression) ported to Rust. That makes the sound example usable on windows with wasapi   👍 and makes timing a lot more stable in general, when used with slightly irregular audio callbacks on some platforms. 

This only concerns system audio callbacks though. If you just need Link for LEDs and UI, this doesn't matter as much.

**Comment by fhennig** [comment] 2022-10-21 09:12
Interesting. I was wondering how the ableton link clock relates to the driver clock. CPAL puts out the time of capture of the buffer with the `StreamInstant` which uses the same time source as ableton link, on Mac at least. If I have beats, I'd really like to correlate the Ableton Link beats back to buffers or even individual samples.

If I have something to contribute, I definitely will!

**Comment by anzbert** [comment] 2022-10-21 10:03
yep thats exactly the challenge. not all platforms provide an exact sample clock next to the system clock in the audio callback, which is why cpal doesnt do it either, since they want to provide an abstraction that works on all platforms. Apparently coreaudio on mac and ios does it well though. This is all described in the 'Time and Clocks' bit of the [Ableton Link readme](https://github.com/Ableton/link/blob/master/README.md).

That is why Ableton provides this HostTimeFilter construct in the C++ code which lets you align a sampleframe counter with the hosttime, to synchronise the two. Since this filter has not been linked to in 'abl_link', I've just quickly ported it to Rust and it works a treat! That also saved creating any more links to C, and staying on the Rust side instead.

You can test it in the 'debugging' branch. At the moment it's pretty messy pre-refactor code though, so beware 😝

PS... the coal streamInstant object has not been overly useful to me, since it hides any real value and I can get a good absolute numbered host clock from the link library with `clock_micos()`. I have only used the coal streaminstant to get an estimated output latency by substracting the playback streaminstant from the invoke streaminstant  . I wonder how accurate that is though across platforms. 

Sure let me know if you have any suggestions. I'd love to get another opinion!

EDIT: The host time filter is in the master branch now and released in v0.3.1.

**Closed as completed** 2023-09-24 08:24 UTC
